type RdioScannerCall {
    id: String
    audio: Audio
    audioName: String
    audioType: String
    emergency: Boolean
    freq: Int
    freqList: [RdioScannerCallFreq]
    startTime: Date
    stopTime: Date
    srcList: [RdioScannerCallSrc]
    system: Int
    talkgroup: Int
}
